
logging.config: classpath:log-prod.xml


spring:
  datasource:
    url: jdbc:mysql://192.168.87.110:63307/gc_ods?useAffectedRows=true&useSSL=false&useUnicode=true&characterEncoding=utf8&autoReconnect=true&zeroDateTimeBehavior=convertToNull&tinyInt1isBit=false&statementInterceptors=com.github.util.sql.PrintSql5
    # driver-class-name: com.mysql.jdbc.Driver  # If use mysql 5
    username: ods_pt_test_q
    password: ZAiw3WFK2BvuIdKy
    hikari:
      minimumIdle: 1
      maximumPoolSize: 1
      maxLifetime: 1500000
  elasticsearch.rest:
    uris: 192.168.86.196:9200


db2es:
  cron: 0/5 * * * * *
  relation:
    -
      table: t_property
      increment-column: id
      limit: 5000
    -
      table: t_value
      increment-column: id
      limit: 2000
