
spring.datasource:
  url: jdbc:mysql://127.0.0.1:3306/db?useSSL=false&useUnicode=true&characterEncoding=utf8&autoReconnect=true&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true
  username: root
  password: root
  hikari:
    minimumIdle: 10
    maximumPoolSize: 30
    dataSourceProperties:
      prepStmtCacheSize: 250
      prepStmtCacheSqlLimit: 2048
      cachePrepStmts: true
      useServerPrepStmts: true

config:
  cron: 0/5 * * * * *
  index: db
  relation:
    -
      table: t_property
      increment-column: ["id"]
      limit: 100
    -
      table: t_value
      increment-column: ["id"]
      limit: 80
