
DROP TABLE IF EXISTS `T_PRODUCT`;
CREATE TABLE IF NOT EXISTS `T_PRODUCT` (
  `ID` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,

  `NAME` VARCHAR(128) NOT NULL COMMENT '商品名',

  `CREATE_TIME` DATETIME NOT NULL COMMENT '创建时间',
  `UPDATE_TIME` DATETIME NOT NULL COMMENT '更新时间',
  `IS_DELETE` TINYINT(1) NOT NULL DEFAULT '0' COMMENT '是否删除(1.已删除, 0.未删除). 默认是 0',
  PRIMARY KEY (`ID`)
) ENGINE=INNODB DEFAULT CHARSET=UTF8MB4 COMMENT='商品';


DROP TABLE IF EXISTS `T_CONTENT`;
CREATE TABLE IF NOT EXISTS `T_CONTENT` (
	`ID` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,

	`TYPE_ID` BIGINT(20) UNSIGNED NOT NULL COMMENT '类型 id(1.散文, 2.短篇, 3.其他 etc...)',
	`URL` VARCHAR(512) NOT NULL COMMENT '数据来源',
	`DATE` DATETIME NOT NULL COMMENT '发布日期',
	`TITLE` VARCHAR(256) NOT NULL COMMENT '标题',
	`CONTENT` LONGTEXT NOT NULL COMMENT '内容',

	`CREATE_TIME` DATETIME NOT NULL COMMENT '创建时间',
	`UPDATE_TIME` DATETIME NOT NULL COMMENT '更新时间',
	`IS_DELETE` TINYINT(1) NOT NULL DEFAULT '0' COMMENT '是否删除(1.已删除, 0.未删除). 默认是 0',
	PRIMARY KEY (`ID`, `TYPE_ID`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8mb4 COMMENT='内容';
